# Generated by Django 3.1.4 on 2021-11-16 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpdate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='文件名称')),
                ('update_time', models.DateTimeField(auto_now_add=True, verbose_name='提交时间')),
                ('files', models.FileField(blank=True, null=True, upload_to='blog_images', verbose_name='博客文件')),
            ],
            options={
                'verbose_name': '博客文件',
                'verbose_name_plural': '博客文件',
            },
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=150, verbose_name='first name'),
        ),
    ]
